# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70337d1dd4c78eaa6583842aae79cc2521028928fce086168930075615ba3ed91ac8d9d2533ed48206b9b09628ecfbe8f51dd155eeb94bd3120d60506f577c09

test:
  secret_key_base: 2738e22868c5045439bcf2f629404661bacf10ecaf18345e2ff968e86ae05c2e5e186ea88d4b4715321c86ecaa40222ab78f54c7a6d424de5f93de0a014525ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
